### ISSUE TITLE
server not running

### ISSUE THREAD

**Issue by sarath-crypto** [samirkumardas/opus-to-pcm#25]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'ws'
Require stack:
- /home/sarath/Work/opus/stream/example/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/sarath/Work/opus/stream/example/server/server.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/sarath/Work/opus/stream/example/server/server.js' ]
}
sarath@shadow:~/Work/opus/stream/example/server$ vi server.js 
sarath@shadow:~/Work/opus/stream/example/server$

**Comment by samirkumardas** [comment]
Run this command `npm install -g npm`

**Comment by sarath-crypto** [comment]
No change Still showing "

Upgrade Required"
